name: DEV | Media Keeper

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/media_keeper:dev
      - name: Login in DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }}
      - name: Pushing docker image
        run: docker push ${{ secrets.DOCKER_USER }}/media_keeper:dev
